version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - deps-{{ checksum "bower.json" }}-{{ checksum "package.json" }}

      - run:
          command: |
            yarn add --dev bower purescript pulp
            git checkout -- package.json

      - save_cache:
          paths:
            - node_modules
            - bower_components
            - output
          key: deps-{{ checksum "bower.json" }}-{{ checksum "package.json" }}

      - run:
          command: |
            yarn test
